# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CurrentListForm.ui'
#
# Created: Sat Aug 11 18:48:04 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CurrentListForm(object):
    def setupUi(self, CurrentListForm):
        CurrentListForm.setObjectName(_fromUtf8("CurrentListForm"))
        CurrentListForm.resize(380, 304)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(CurrentListForm)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.currentGroup = QtGui.QGroupBox(CurrentListForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentGroup.sizePolicy().hasHeightForWidth())
        self.currentGroup.setSizePolicy(sizePolicy)
        self.currentGroup.setObjectName(_fromUtf8("currentGroup"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.currentGroup)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.currentList = QtGui.QTableView(self.currentGroup)
        self.currentList.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.currentList.setAcceptDrops(True)
        self.currentList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.currentList.setDragEnabled(True)
        self.currentList.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.currentList.setAlternatingRowColors(True)
        self.currentList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.currentList.setTextElideMode(QtCore.Qt.ElideNone)
        self.currentList.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.currentList.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.currentList.setShowGrid(False)
        self.currentList.setWordWrap(False)
        self.currentList.setObjectName(_fromUtf8("currentList"))
        self.currentList.horizontalHeader().setVisible(False)
        self.currentList.horizontalHeader().setMinimumSectionSize(2)
        self.currentList.verticalHeader().setVisible(False)
        self.currentList.verticalHeader().setDefaultSectionSize(2)
        self.currentList.verticalHeader().setMinimumSectionSize(2)
        self.verticalLayout_4.addWidget(self.currentList)
        self.playlistTools = QtGui.QWidget(self.currentGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlistTools.sizePolicy().hasHeightForWidth())
        self.playlistTools.setSizePolicy(sizePolicy)
        self.playlistTools.setObjectName(_fromUtf8("playlistTools"))
        self.toolsLayout = QtGui.QGridLayout(self.playlistTools)
        self.toolsLayout.setContentsMargins(3, 1, 1, 1)
        self.toolsLayout.setObjectName(_fromUtf8("toolsLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.playlistTools)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.currentFilter = KLineEdit(self.playlistTools)
        self.currentFilter.setProperty("showClearButton", True)
        self.currentFilter.setObjectName(_fromUtf8("currentFilter"))
        self.horizontalLayout.addWidget(self.currentFilter)
        self.toolsLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.oneLinePlaylist = QtGui.QCheckBox(self.playlistTools)
        self.oneLinePlaylist.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.oneLinePlaylist.setObjectName(_fromUtf8("oneLinePlaylist"))
        self.toolsLayout.addWidget(self.oneLinePlaylist, 1, 0, 1, 1)
        self.keepPlayingVisible = QtGui.QCheckBox(self.playlistTools)
        self.keepPlayingVisible.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepPlayingVisible.sizePolicy().hasHeightForWidth())
        self.keepPlayingVisible.setSizePolicy(sizePolicy)
        self.keepPlayingVisible.setObjectName(_fromUtf8("keepPlayingVisible"))
        self.toolsLayout.addWidget(self.keepPlayingVisible, 2, 0, 1, 1)
        self.showNumbers = QtGui.QCheckBox(self.playlistTools)
        self.showNumbers.setObjectName(_fromUtf8("showNumbers"))
        self.toolsLayout.addWidget(self.showNumbers, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(26, -1, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.playlistTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.crossFade = QtGui.QSpinBox(self.playlistTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crossFade.sizePolicy().hasHeightForWidth())
        self.crossFade.setSizePolicy(sizePolicy)
        self.crossFade.setMaximumSize(QtCore.QSize(45, 16777215))
        self.crossFade.setObjectName(_fromUtf8("crossFade"))
        self.horizontalLayout_3.addWidget(self.crossFade)
        self.label = QtGui.QLabel(self.playlistTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.toolsLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.currentClear = QtGui.QPushButton(self.playlistTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentClear.sizePolicy().hasHeightForWidth())
        self.currentClear.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ui/icons/edit-clear-list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.currentClear.setIcon(icon)
        self.currentClear.setObjectName(_fromUtf8("currentClear"))
        self.toolsLayout.addWidget(self.currentClear, 4, 1, 1, 1)
        self.currentRemove = QtGui.QPushButton(self.playlistTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentRemove.sizePolicy().hasHeightForWidth())
        self.currentRemove.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("ui/icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.currentRemove.setIcon(icon1)
        self.currentRemove.setObjectName(_fromUtf8("currentRemove"))
        self.toolsLayout.addWidget(self.currentRemove, 3, 1, 1, 1)
        self.currentSave = QtGui.QPushButton(self.playlistTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentSave.sizePolicy().hasHeightForWidth())
        self.currentSave.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("ui/icons/document-save-as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.currentSave.setIcon(icon2)
        self.currentSave.setObjectName(_fromUtf8("currentSave"))
        self.toolsLayout.addWidget(self.currentSave, 1, 1, 1, 1)
        self.addStream = QtGui.QPushButton(self.playlistTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStream.sizePolicy().hasHeightForWidth())
        self.addStream.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("ui/icons/network-workgroup.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addStream.setIcon(icon3)
        self.addStream.setObjectName(_fromUtf8("addStream"))
        self.toolsLayout.addWidget(self.addStream, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.playlistTools)
        self.horizontalWidget = QtGui.QWidget(self.currentGroup)
        self.horizontalWidget.setObjectName(_fromUtf8("horizontalWidget"))
        self.currentBottomL = QtGui.QHBoxLayout(self.horizontalWidget)
        self.currentBottomL.setMargin(0)
        self.currentBottomL.setMargin(0)
        self.currentBottomL.setObjectName(_fromUtf8("currentBottomL"))
        self.currentBottom = QtGui.QToolButton(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentBottom.sizePolicy().hasHeightForWidth())
        self.currentBottom.setSizePolicy(sizePolicy)
        self.currentBottom.setCheckable(False)
        self.currentBottom.setChecked(False)
        self.currentBottom.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.currentBottom.setAutoRaise(True)
        self.currentBottom.setArrowType(QtCore.Qt.UpArrow)
        self.currentBottom.setObjectName(_fromUtf8("currentBottom"))
        self.currentBottomL.addWidget(self.currentBottom)
        self.repeatButton = QtGui.QPushButton(self.horizontalWidget)
        self.repeatButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repeatButton.sizePolicy().hasHeightForWidth())
        self.repeatButton.setSizePolicy(sizePolicy)
        self.repeatButton.setMaximumSize(QtCore.QSize(26, 26))
        self.repeatButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("ui/icons/task-recurring.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.repeatButton.setIcon(icon4)
        self.repeatButton.setCheckable(True)
        self.repeatButton.setFlat(True)
        self.repeatButton.setObjectName(_fromUtf8("repeatButton"))
        self.currentBottomL.addWidget(self.repeatButton)
        self.randomButton = QtGui.QPushButton(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randomButton.sizePolicy().hasHeightForWidth())
        self.randomButton.setSizePolicy(sizePolicy)
        self.randomButton.setMaximumSize(QtCore.QSize(26, 26))
        self.randomButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("ui/icons/media-playlist-shuffle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.randomButton.setIcon(icon5)
        self.randomButton.setCheckable(True)
        self.randomButton.setFlat(True)
        self.randomButton.setObjectName(_fromUtf8("randomButton"))
        self.currentBottomL.addWidget(self.randomButton)
        self.verticalLayout_4.addWidget(self.horizontalWidget)
        self.horizontalLayout_2.addWidget(self.currentGroup)
        self.label_4.setBuddy(self.currentFilter)
        self.label_7.setBuddy(self.crossFade)

        self.retranslateUi(CurrentListForm)
        QtCore.QMetaObject.connectSlotsByName(CurrentListForm)

    def retranslateUi(self, CurrentListForm):
        CurrentListForm.setWindowTitle(QtGui.QApplication.translate("CurrentListForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.currentGroup.setTitle(QtGui.QApplication.translate("CurrentListForm", "Current Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CurrentListForm", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.oneLinePlaylist.setText(QtGui.QApplication.translate("CurrentListForm", "Use one line per playlist item.", None, QtGui.QApplication.UnicodeUTF8))
        self.keepPlayingVisible.setText(QtGui.QApplication.translate("CurrentListForm", "Keep current song visible", None, QtGui.QApplication.UnicodeUTF8))
        self.showNumbers.setText(QtGui.QApplication.translate("CurrentListForm", "Show song numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CurrentListForm", "XFade", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CurrentListForm", "seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.currentClear.setText(QtGui.QApplication.translate("CurrentListForm", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.currentRemove.setText(QtGui.QApplication.translate("CurrentListForm", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.currentSave.setText(QtGui.QApplication.translate("CurrentListForm", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.addStream.setText(QtGui.QApplication.translate("CurrentListForm", "Add Stream", None, QtGui.QApplication.UnicodeUTF8))
        self.currentBottom.setText(QtGui.QApplication.translate("CurrentListForm", "Show Playlist Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatButton.setToolTip(QtGui.QApplication.translate("CurrentListForm", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.randomButton.setToolTip(QtGui.QApplication.translate("CurrentListForm", "Random", None, QtGui.QApplication.UnicodeUTF8))

from PyKDE4.kdeui import KLineEdit
